trigger:
  batch: true
  branches:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'

resources:
  repositories:
    - repository: GodelTech
      type: github
      endpoint: 'godeltech'
      name: 'GodelTech/AzureDevOps.Pipeline.Templates'
      ref: 'refs/tags/v5.0.1'

extends:
  template: '.NET Core/NuGet.yml@GodelTech'
  parameters:
    sonarCloudOrganizationName: 'godeltech'
    artifactPackDirectory: 'packages'
    internalFeed: '19324bbd-9baf-4407-b86d-3e7f0d145399/1574777e-9941-4b90-baa9-d9938266ac24'
    # Use preBuildSteps 
    preBuildSteps: 
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK 3.1.x for support both frameworks'
      inputs:
        packageType: 'sdk'
        version: '3.1.x'
